//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fahrenheittocelsiusconversion.azurewebsites.net/", ConfigurationName="ServiceReference1.IConversionService")]
    public interface IConversionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fahrenheittocelsiusconversion.azurewebsites.net/IConversionService/Fahrenh" +
            "eitToCelsius", ReplyAction="http://fahrenheittocelsiusconversion.azurewebsites.net/IConversionService/Fahrenh" +
            "eitToCelsiusResponse")]
        double FahrenheitToCelsius(double farenheitDegrees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fahrenheittocelsiusconversion.azurewebsites.net/IConversionService/Fahrenh" +
            "eitToCelsius", ReplyAction="http://fahrenheittocelsiusconversion.azurewebsites.net/IConversionService/Fahrenh" +
            "eitToCelsiusResponse")]
        System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double farenheitDegrees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fahrenheittocelsiusconversion.azurewebsites.net/IConversionService/Celsius" +
            "ToFahrenheit", ReplyAction="http://fahrenheittocelsiusconversion.azurewebsites.net/IConversionService/Celsius" +
            "ToFahrenheitResponse")]
        double CelsiusToFahrenheit(double celsiusDegrees);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fahrenheittocelsiusconversion.azurewebsites.net/IConversionService/Celsius" +
            "ToFahrenheit", ReplyAction="http://fahrenheittocelsiusconversion.azurewebsites.net/IConversionService/Celsius" +
            "ToFahrenheitResponse")]
        System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsiusDegrees);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConversionServiceChannel : WindowsFormsApp1.ServiceReference1.IConversionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConversionServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IConversionService>, WindowsFormsApp1.ServiceReference1.IConversionService {
        
        public ConversionServiceClient() {
        }
        
        public ConversionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConversionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double FahrenheitToCelsius(double farenheitDegrees) {
            return base.Channel.FahrenheitToCelsius(farenheitDegrees);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double farenheitDegrees) {
            return base.Channel.FahrenheitToCelsiusAsync(farenheitDegrees);
        }
        
        public double CelsiusToFahrenheit(double celsiusDegrees) {
            return base.Channel.CelsiusToFahrenheit(celsiusDegrees);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double celsiusDegrees) {
            return base.Channel.CelsiusToFahrenheitAsync(celsiusDegrees);
        }
    }
}
